FROM arm64v8/alpine:3.5 as build
RUN apk add --no-cache build-base ncurses-dev zlib-dev wget flex perl libc6-compat

WORKDIR /tmp

# Build Apache 2.2
ADD httpd-2.2.34.tar.bz2 .
RUN cd httpd-2.2.34 \
  &&./configure --prefix=/usr/local/apache2 --enable-mods-shared=all --enable-deflate --enable-proxy --enable-proxy-balancer --enable-proxy-http \
  && make \
  && make install

# Build PHP 4
ADD php-4.4.9.tar.bz2 .
ADD php.ini /usr/local/apache2/php.ini

WORKDIR /tmp/php-4.4.9
RUN ./configure --with-apxs2=/usr/local/apache2/bin/apxs --with-mysql --enable-force-cgi-redirect --disable-cgi --with-zlib --with-config-file-path=/usr/local/apache2 --host=aarch64-unknown-linux-gnu
RUN sed -i "/CFLAGS_CLEAN =/c\CFLAGS_CLEAN = -g -O2 -fcommon" Makefile
RUN sed -i "/CPP =/c\CPP = gcc -E -fcommon" Makefile
# libtool's file_magic check is broken on aarch64/musl: it rejects valid shared
# libs (libz, musl libc) and falls back to a static libphp4.a, so no libphp4.so
# is produced and apxs fails. Force pass_all so libtool trusts the linker.
RUN sed -i 's/^deplibs_check_method=.*/deplibs_check_method="pass_all"/' libtool
RUN make && make install

WORKDIR /tmp

# Setup PHP to Run on Apache
RUN echo 'AddType application/x-httpd-php php' >> /usr/local/apache2/conf/httpd.conf \
  && sed -i 's/DirectoryIndex index.html/DirectoryIndex index.php index.html/' /usr/local/apache2/conf/httpd.conf

# Build Mysql 4
ADD mysql-4.1.22.tar.bz2 .

RUN echo '/* Linuxthreads */' >> /usr/include/pthread.h
WORKDIR /tmp/mysql-4.1.22
RUN ./configure --prefix=/usr/local/mysql --build=aarch64-unknown-linux-gnu CXXFLAGS="-std=gnu++98 -fpermissive"
RUN sed -i "/HAVE_GETHOSTBYADDR_R/d" config.h
RUN sed -i "/HAVE_GETHOSTBYNAME_R/d" config.h
RUN make && make install

WORKDIR /tmp

# Linuxtrheads hack explained: https://bugs.mysql.com/bug.php?id=19785
# gnu++98 (error: narrowing conversion):  https://bugs.mysql.com/bug.php?id=19785
# libc6-compat solves the problem of missing libm.so on aarch64

FROM arm64v8/alpine

RUN apk add --no-cache libstdc++ tzdata

# Setup Mysql to Run
ADD my.cnf /usr/local/mysql/my.cnf
RUN addgroup -S mysql && adduser -S mysql -G mysql \
  && mkdir /usr/local/mysql/var \
  && chown -R root /usr/local/mysql && chown -R mysql /usr/local/mysql/var && chgrp -R mysql /usr/local/mysql

COPY --from=build /usr/local/apache2 /usr/local/apache2
COPY --from=build /usr/local/mysql /usr/local/mysql

ENV PATH="${PATH}:/usr/local/apache2/bin/:/usr/local/mysql/bin/"
VOLUME /usr/local/mysql/var /usr/local/apache2/htdocs/
EXPOSE 80 
CMD apachectl start \
    && chown daemon -R /usr/local/apache2/htdocs/ \
    && chown mysql -R /usr/local/mysql/var/ \
    && mysqld_safe --defaults-file=/usr/local/mysql/my.cnf 
